# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Fred Hohman
tagline:          'Ph.D. Student in CSE at GT'
description:      'Ph.D. Student in CSE at GT.'
url:              http://fredhohman.com

author:
  name:           'Fred Hohman'
  url:            https://twitter.com/fredhohman

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/fredhohman/fredhohman.github.io

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'