title: Fred Hohman
tagline: PhD Candidate at GT
url: http://fredhohman.com
baseurl: ""
# gems: [jekyll-paginate]
# paginate: 5

# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink: "/:title"
# relative_permalinks: true

sass:
  sass_dir: _sass
  style: compressed

author:
  name: Fred Hohman
  url: http://fredhohman.com
  email: fred.hohman@gmail.edu

excerpt_separator: <!--more-->

plugins:
  - jekyll-sitemap
  - jekyll-feed
